name: Encrypt Secret
author: Soren Olsen
description: Used to encrypt content for repository secrets
inputs:
  key:
    description: "Base64 key for encryption"
    required: true
    default: none
  text:
    description: "Clear text to be encrypted"
    required: true
    default: none
outputs:
  secret:
    description: "Encrypted text"
runs:
  using: "node16"
  main: "index.js"
