on: push
jobs: 
  create_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "bot@gizber.com"
          git config --global user.name "Gizber Bot"
          git fetch
          git checkout workflows
          git branch --set-upstream-to=origin/workflows
          git pull
      - name: Get Branches
        id: branches
        run: |
          branches=$(git branch -r | awk -F\/ '{printf "       - %s\\n", $2}')          
          echo "::set-output name=names::$branches"
      - name: Get public key object
        id: public_key
        run: |
          response=$(curl --silent \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHA_PAT }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key)
          echo "::set-output name=key_id::$(echo $response | jq '.key_id')"
          echo "::set-output name=key::$(echo $response | jq '.key')"
          echo "Key: ${{ steps.public_key.outputs.key }}"
      - name: Echo variable
        run: |
          echo "Key: ${{ steps.public_key.outputs.key }}"
          echo "Branches: ${{ steps.branches.outputs.names }}"
      - uses: ./.github/actions/secrets
        id: secret
        with:
          key: ${{ steps.public_key.outputs.key }}
          text: ${{ steps.branches.outputs.names }}
      - run: |
          echo "Secret: ${{ steps.secret.outputs.secret }}"