name: Select Branch

on:
 workflow_dispatch:
   inputs:
     branch:
       description: 'The feature branch to review'
       required: true
       type: choice
       options:
         - develop
- master
- workflows
     
jobs:
 deployment:
   runs-on: ubuntu-latest
   steps:
    - name: Testing outputs
      run: |
        echo "Choice: ${{ inputs.branch }}"