on: push

jobs:
  verify_input:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        run: |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.PAT_WORKFLOWS }}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "bot@gizber.com"
          git config --global user.name "Gizber Bot"
          git fetch
          git checkout dev
          git branch --set-upstream-to=origin/dev
          git pull
      - name: Get Branch
        id: branch
        run: |
          branch=$(git branch -r --list 'origin/${{ inputs.branch }}')
          echo 'branch=$branch' >> $GITHUB_OUTPUT
          echo $branch
      - name: echo env variable
        run: |
          echo '${{ env.branch }}'
